# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    app.twig_extension:
        class: AppBundle\Controller\Cryptage
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
        - { name: twig.extension }

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
          - { name: serializer.normalizer }

    user_app_check:
        class: AppBundle\Security\CheckUserApp
        arguments: ["@security.token_storage", "@security.authorization_checker", "@doctrine.orm.entity_manager", "@router"]
        public: true

  #serializer
    app.serialize_to_json:
        class: AppBundle\Functions\SerializeToJSON
        public: true

  #success handler
    security.authentication.success_handler:
        class: AppBundle\EventListener\AuthenticationSuccessHandler
        arguments:
          - "@security.http_utils"
          - {}
          - "@doctrine.orm.entity_manager"
          - "@router"
          - "@security.authorization_checker"
        tags:
            - { name: 'monolog.logger', channel: 'security'}

  #Calcul des taches
    tache.calculer:
        class: AppBundle\Functions\TacheHandler
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@templating.engine.twig"

  #Calcul des taches
    tache3.calculer:
        class: AppBundle\Functions\Taches3Handler
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@templating.engine.twig"

    json.twig_extension:
            class: AppBundle\Controller\Json
            public: false
            tags:
                - { name: twig.extension }

    app.twig_filter_route_exists:
        class: AppBundle\Functions\RouteExists
        public: false
        arguments:
          - "@router"
        tags:
            - { name: twig.extension }
            
    twig.twig_filter_html_twig:
         class: AppBundle\Functions\htmlTwig
         tags:
             - { name: twig.extension }
